# Generated by Django 6.0 on 2025-12-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='الشعار')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50, verbose_name='أيقونة')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الخصم')),
                ('size', models.CharField(help_text='مثال: 100ml, 50ml', max_length=50, verbose_name='الحجم')),
                ('image', models.ImageField(upload_to='perfumes/', verbose_name='الصورة الرئيسية')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='صورة إضافية 1')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='صورة إضافية 2')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('in_stock', models.BooleanField(default=True, verbose_name='متوفر')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='perfumes.brand', verbose_name='العلامة التجارية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='perfumes.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'عطر',
                'verbose_name_plural': 'العطور',
                'ordering': ['-created_at'],
            },
        ),
    ]
