# Generated by Django 6.0 on 2025-12-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'طلب جديد'), ('confirmed', 'تم التأكيد'), ('preparing', 'قيد التحضير'), ('shipped', 'تم الشحن'), ('in_transit', 'في الطريق'), ('delivered', 'تم التسليم')], max_length=20, verbose_name='الحالة')),
                ('status_ar', models.CharField(max_length=100, verbose_name='الحالة بالعربية')),
                ('status_en', models.CharField(max_length=100, verbose_name='الحالة بالإنجليزية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحديث')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'حالة الشحنة',
                'verbose_name_plural': 'حالات الشحنة',
                'ordering': ['created_at'],
            },
        ),
    ]
